### ISSUE TITLE
Cannot instantiate type which has no empty constructor

### ISSUE THREAD

**Issue by pantonis** [alphacloud/Autofac.Extras.Quartz#49] opened 2017-12-11 10:23 UTC
I have the following code

```
containerBuilder.RegisterModule(new QuartzAutofacFactoryModule());
containerBuilder.RegisterModule(new QuartzAutofacJobsModule(typeof(CalculatorJob).Assembly));

public class CalculatorJob : IJob
    {
        private readonly ICalculator calculator;

        public CalculatorJob(ICalculator calculator)
        {
            this.calculator = calculator;
        }

        public void Execute(IJobExecutionContext context)
        {
            calculator.PerformCalculator();
        }
    }
```

and I get following error
```
  - FirstChance Exception  -- Cannot instantiate type which has no empty constructor
Parameter name: CalculatorJob
System.ArgumentException: Cannot instantiate type which has no empty constructor
Parameter name: CalculatorJob
   at Quartz.Util.ObjectUtils.InstantiateType[T](Type type) in c:\projects\quartznet-6fcn8\src\Quartz\Util\ObjectUtils.cs:line 107
Exception thrown: 'Quartz.SchedulerException' in Quartz.dll
SchedulerTest1.Service.Program: FATAL 2017-12-11 12:21:26,442 [DefaultQuartzScheduler_QuartzSchedulerThread] SchedulerTest1.Service.Program           - FirstChance Exception  -- Problem instantiating class 'SchedulerTest1.Infrastracture.Jobs.CalculatorJob'
Quartz.SchedulerException: Problem instantiating class 'SchedulerTest1.Infrastracture.Jobs.CalculatorJob' ---> System.ArgumentException: Cannot instantiate type which has no empty constructor
Parameter name: CalculatorJob
   at Quartz.Util.ObjectUtils.InstantiateType[T](Type type) in c:\projects\quartznet-6fcn8\src\Quartz\Util\ObjectUtils.cs:line 107
   at Quartz.Simpl.SimpleJobFactory.NewJob(TriggerFiredBundle bundle, IScheduler scheduler) in c:\projects\quartznet-6fcn8\src\Quartz\Simpl\SimpleJobFactory.cs:line 68
   --- End of inner exception stack trace ---
   at Quartz.Simpl.SimpleJobFactory.NewJob(TriggerFiredBundle bundle, IScheduler scheduler) in c:\projects\quartznet-6fcn8\src\Quartz\Simpl\SimpleJobFactory.cs:line 76 [See nested exception: System.ArgumentException: Cannot instantiate type which has no empty constructor
Parameter name: CalculatorJob
   at Quartz.Util.ObjectUtils.InstantiateType[T](Type type) in c:\projects\quartznet-6fcn8\src\Quartz\Util\ObjectUtils.cs:line 107
   at Quartz.Simpl.SimpleJobFactory.NewJob(TriggerFiredBundle bundle, IScheduler scheduler) in c:\projects\quartznet-6fcn8\src\Quartz\Simpl\SimpleJobFactory.cs:line 68]
Exception thrown: 'Quartz.SchedulerException' in Quartz.dll
SchedulerTest1.Service.Program: FATAL 2017-12-11 12:21:26,457 [DefaultQuartzScheduler_QuartzSchedulerThread] SchedulerTest1.Service.Program           - FirstChance Exception  -- Problem instantiating class 'SchedulerTest1.Infrastracture.Jobs.CalculatorJob'
Quartz.SchedulerException: Problem instantiating class 'SchedulerTest1.Infrastracture.Jobs.CalculatorJob' ---> System.ArgumentException: Cannot instantiate type which has no empty constructor
Parameter name: CalculatorJob
   at Quartz.Util.ObjectUtils.InstantiateType[T](Type type) in c:\projects\quartznet-6fcn8\src\Quartz\Util\ObjectUtils.cs:line 107
   at Quartz.Simpl.SimpleJobFactory.NewJob(TriggerFiredBundle bundle, IScheduler scheduler) in c:\projects\quartznet-6fcn8\src\Quartz\Simpl\SimpleJobFactory.cs:line 68
   --- End of inner exception stack trace ---
   at Quartz.Simpl.SimpleJobFactory.NewJob(TriggerFiredBundle bundle, IScheduler scheduler) in c:\projects\quartznet-6fcn8\src\Quartz\Simpl\SimpleJobFactory.cs:line 76
   at Quartz.Simpl.PropertySettingJobFactory.NewJob(TriggerFiredBundle bundle, IScheduler scheduler) in c:\projects\quartznet-6fcn8\src\Quartz\Simpl\PropertySettingJobFactory.cs:line 95
   at Quartz.Core.JobRunShell.Initialize(QuartzScheduler sched) in c:\projects\quartznet-6fcn8\src\Quartz\Core\JobRunShell.cs:line 96 [See nested exception: System.ArgumentException: Cannot instantiate type which has no empty constructor
Parameter name: CalculatorJob
   at Quartz.Util.ObjectUtils.InstantiateType[T](Type type) in c:\projects\quartznet-6fcn8\src\Quartz\Util\ObjectUtils.cs:line 107
   at Quartz.Simpl.SimpleJobFactory.NewJob(TriggerFiredBundle bundle, IScheduler scheduler) in c:\projects\quartznet-6fcn8\src\Quartz\Simpl\SimpleJobFactory.cs:line 68]
```

**Comment by shatl** [comment] 2017-12-12 13:30
Looks like autofac us not used to resolve CalculatorJob.

**Comment by pantonis** [comment] 2017-12-12 14:07
but why is that happening? Code above should work...

**Comment by shatl** [comment] 2017-12-13 23:30
Make sure you resolving IScheduler from container not using default one, see https://github.com/alphacloud/Autofac.Extras.Quartz#starting-quartz.

If this does not help, please share your startup code or create simple project which reproduces the issue.

**Comment by pantonis** [comment] 2017-12-14 09:10
that is how I am doing it and still does not work. Here is my sample project
[SchedulerTest1](https://1drv.ms/u/s!AJ6vT6kvVLZ0jGI)

**Comment by pantonis** [comment] 2017-12-24 12:41
@shatl did you check the sample project I sent?

**Comment by shatl** [comment] 2017-12-26 15:27
@pantonis You are not resolving scheduler from Autofac. Please check the link I send you earlier.

**Closed by shatl** 2017-12-26 15:27 UTC

**Comment by pantonis** [comment] 2017-12-27 17:35
@shatl Thanks.

May I ask what is the Lifetime of the IScheduler?
